### ISSUE TITLE
Fail to compile, missing gdb

### ISSUE THREAD

**Issue by TheMeaningfulEngineer** [herrgahr/qling#1]
Hy!

I'm following your instructions to compile qling, and I'm getting.

WARNING: Failure to find: gdb/gdb.cpp
WARNING: Failure to find: gdb/gdb.h

I have installed `qt4-qmake` and `gdb-dev` to try to resolve the problem, but it didn't help. My llvm, cling and cland executables are all located in the home folder (ono is in usr/src or similar)

**Comment by ghost** [comment]
First of all: sorry for the late reply, the notifications got lost in my email-filter.
I updated the master branch to work with the latest git version of cling.
The build should work fine now.
